prompt_template:
  input_variables: ["query"]
  template: |
    너는 사용자의 질문을 분석해서 가장 적합한 처리 방법을 선택해야 해.

    사용자 질문:
    {query}

    - 'vectordb': 사실 기반 데이터 검색이 필요한 경우(질문에 금융보안원, 일본 여행 이 들어간 경우)
    - 'ml': 계좌번호 관련 예측 모델이 필요한 경우(계좌번호 예시 : 100-117-989847)
    - 'llm': 자유로운 창작 또는 대화형 답변이 필요한 경우

    반드시 route_decision 함수를 호출해서 결정해.
    추가 설명은 하지 마.